### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by s-ludwig** [lionello/jpeg-turbo#4]
Hi! I just discovered the bindings and stumbled over the missing turbjpeg header and the deprecation warnings of the current 1.3.0 tag. Would be great if you would tag a new 1.3.1 release for HEAD, so that the changes become available via DUB.

**Comment by lionello** [comment]
Done. Let me know if this fixed the issue.

**Comment by s-ludwig** [comment]
Sorry, forgot to prepend the necessary "v" when citing the tag names ("v1.3.1")! Otherwise it won't be picked up by the registry. Thanks for the quick reaction!

**Comment by lionello** [comment]
Done
